/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package MyApp;

import MyLibs.*;
import java.util.ArrayList;
import java.util.Random;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Yumeno
 */
public class MainMenu extends javax.swing.JFrame {
    
    ArrayList<Block> blocks = new ArrayList<>();
    Manager manager;
    int minPrice = 5000, maxPrice = 15000, minSize = 40, maxSize = 250, blockLimit = 5, lotLimit = 20;
    public MainMenu() {
        initComponents();
        // Default hardcoded data
        //randomized 40-200 for size, price = 5000-15000, 
        for (int i = 0; i < blockLimit; i++) {
            Block block = new Block(i + 1);
            for (int j = 0; j < lotLimit; j++) {
                Random rPrice = new Random();
                Random rSize = new Random();
                float price = rPrice.nextInt(maxPrice-minPrice)+minPrice;
                float size = rSize.nextInt(maxSize-minSize)+minSize;
                Lot lot = new Lot(size, j + 1, price);
                block.getLots().add(lot);
            }
            blocks.add(block);
        }
        manager = new Manager(blocks);
        DefaultTableModel model = (DefaultTableModel) sTable.getModel();
        model.setRowCount(0);
        for (Block block : manager.getArrayList()) {
            for (Lot lot : block.getLots()) {
                model.addRow(new Object[]{
                    block.getBlockNum(), lot.getLotNum(), lot.getSize(), lot.getPrice()}
                );
            }
        }    
        sTable.setAutoCreateRowSorter(true);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        parentPanel = new javax.swing.JPanel();
        mainMenu = new javax.swing.JPanel();
        modLotsButton = new javax.swing.JButton();
        showLotButton = new javax.swing.JButton();
        procLotsButton = new javax.swing.JButton();
        genRepButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        modifyLots = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        backButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        mBlockFld = new javax.swing.JTextField();
        mSizeFld = new javax.swing.JTextField();
        mPriceFld = new javax.swing.JTextField();
        modifyButton = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        mLotFld = new javax.swing.JTextField();
        mClearBtn = new javax.swing.JButton();
        showLots = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        backButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        sTable = new javax.swing.JTable();
        sRefreshBtn = new javax.swing.JButton();
        processLots = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        pLotFld = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        pStatusCbx = new javax.swing.JComboBox<>();
        backButton3 = new javax.swing.JButton();
        pSubmitBtn = new javax.swing.JButton();
        pBlockCbx = new javax.swing.JComboBox<>();
        clientFirstFld = new javax.swing.JTextField();
        clientLastFld = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        genRep = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        backButton4 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        gTable = new javax.swing.JTable();
        gBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        parentPanel.setLayout(new java.awt.CardLayout());

        modLotsButton.setFont(new java.awt.Font("Sitka Display", 1, 24)); // NOI18N
        modLotsButton.setText("Modify Lots");
        modLotsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modLotsButtonActionPerformed(evt);
            }
        });

        showLotButton.setFont(new java.awt.Font("Sitka Display", 1, 24)); // NOI18N
        showLotButton.setText("Show Lots");
        showLotButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showLotButtonActionPerformed(evt);
            }
        });

        procLotsButton.setFont(new java.awt.Font("Sitka Display", 1, 24)); // NOI18N
        procLotsButton.setText("Process Lots");
        procLotsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                procLotsButtonActionPerformed(evt);
            }
        });

        genRepButton.setFont(new java.awt.Font("Sitka Display", 1, 24)); // NOI18N
        genRepButton.setText("Generate Report");
        genRepButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genRepButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Sitka Heading", 1, 36)); // NOI18N
        jLabel1.setText("Welcome!");
        jLabel1.setToolTipText("");

        javax.swing.GroupLayout mainMenuLayout = new javax.swing.GroupLayout(mainMenu);
        mainMenu.setLayout(mainMenuLayout);
        mainMenuLayout.setHorizontalGroup(
            mainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainMenuLayout.createSequentialGroup()
                .addGap(247, 247, 247)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainMenuLayout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(mainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(modLotsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(procLotsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(mainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(showLotButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(genRepButton, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16))
        );
        mainMenuLayout.setVerticalGroup(
            mainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainMenuLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(mainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modLotsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(showLotButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(mainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(procLotsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(genRepButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(81, Short.MAX_VALUE))
        );

        parentPanel.add(mainMenu, "card2");

        jLabel2.setFont(new java.awt.Font("Sitka Heading", 1, 36)); // NOI18N
        jLabel2.setText("Modify Lots");
        jLabel2.setToolTipText("");

        backButton1.setText("Back");
        backButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButton1ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Sitka Text", 0, 18)); // NOI18N
        jLabel6.setText("Block:");

        jLabel7.setFont(new java.awt.Font("Sitka Text", 0, 18)); // NOI18N
        jLabel7.setText("Size:");

        jLabel8.setFont(new java.awt.Font("Sitka Text", 0, 18)); // NOI18N
        jLabel8.setText("Price:");

        modifyButton.setText("Submit");
        modifyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifyButtonActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Sitka Text", 0, 18)); // NOI18N
        jLabel14.setText("Lot:");

        mClearBtn.setText("Clear");
        mClearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mClearBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout modifyLotsLayout = new javax.swing.GroupLayout(modifyLots);
        modifyLots.setLayout(modifyLotsLayout);
        modifyLotsLayout.setHorizontalGroup(
            modifyLotsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, modifyLotsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(216, 216, 216))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, modifyLotsLayout.createSequentialGroup()
                .addGap(156, 156, 156)
                .addGroup(modifyLotsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel6)
                    .addComponent(modifyButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addGroup(modifyLotsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, modifyLotsLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(mClearBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(backButton1))
                    .addComponent(mPriceFld)
                    .addComponent(mSizeFld)
                    .addComponent(mBlockFld)
                    .addComponent(mLotFld, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(117, 117, 117))
        );
        modifyLotsLayout.setVerticalGroup(
            modifyLotsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(modifyLotsLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addGroup(modifyLotsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(mBlockFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(modifyLotsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(mLotFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(modifyLotsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(mSizeFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(modifyLotsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(mPriceFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                .addGroup(modifyLotsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mClearBtn)
                    .addComponent(modifyButton)
                    .addComponent(backButton1))
                .addGap(86, 86, 86))
        );

        parentPanel.add(modifyLots, "card3");

        jLabel3.setFont(new java.awt.Font("Sitka Heading", 1, 36)); // NOI18N
        jLabel3.setText("Show Lots");
        jLabel3.setToolTipText("");

        backButton2.setText("Back");
        backButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButton2ActionPerformed(evt);
            }
        });

        sTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Block", "Lot", "Size", "Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Float.class, java.lang.Float.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(sTable);

        sRefreshBtn.setText("Refresh");
        sRefreshBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sRefreshBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout showLotsLayout = new javax.swing.GroupLayout(showLots);
        showLots.setLayout(showLotsLayout);
        showLotsLayout.setHorizontalGroup(
            showLotsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(showLotsLayout.createSequentialGroup()
                .addGap(249, 249, 249)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(showLotsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(showLotsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(showLotsLayout.createSequentialGroup()
                        .addComponent(sRefreshBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(backButton2))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 596, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        showLotsLayout.setVerticalGroup(
            showLotsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(showLotsLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(showLotsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backButton2)
                    .addComponent(sRefreshBtn))
                .addContainerGap(104, Short.MAX_VALUE))
        );

        parentPanel.add(showLots, "card4");

        jLabel4.setFont(new java.awt.Font("Sitka Heading", 1, 36)); // NOI18N
        jLabel4.setText("Process Lots");
        jLabel4.setToolTipText("");

        jLabel12.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        jLabel12.setText("Block No.");

        jLabel15.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        jLabel15.setText("Lot No.");

        jLabel16.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        jLabel16.setText("Change Status:");

        pStatusCbx.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Available", "Reserved", "Sold" }));

        backButton3.setText("Back");
        backButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButton3ActionPerformed(evt);
            }
        });

        pSubmitBtn.setText("Submit");
        pSubmitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pSubmitBtnActionPerformed(evt);
            }
        });

        pBlockCbx.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5" }));

        clientFirstFld.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N

        clientLastFld.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        jLabel9.setText("First name:");

        jLabel10.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        jLabel10.setText("Last name:");

        javax.swing.GroupLayout processLotsLayout = new javax.swing.GroupLayout(processLots);
        processLots.setLayout(processLotsLayout);
        processLotsLayout.setHorizontalGroup(
            processLotsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(processLotsLayout.createSequentialGroup()
                .addContainerGap(159, Short.MAX_VALUE)
                .addGroup(processLotsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, processLotsLayout.createSequentialGroup()
                        .addGroup(processLotsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))
                        .addGap(87, 87, 87)
                        .addGroup(processLotsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pLotFld)
                            .addComponent(pStatusCbx, 0, 182, Short.MAX_VALUE)
                            .addComponent(pBlockCbx, 0, 182, Short.MAX_VALUE)
                            .addComponent(clientFirstFld)
                            .addComponent(clientLastFld))
                        .addGap(126, 126, 126))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, processLotsLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(227, 227, 227))))
            .addGroup(processLotsLayout.createSequentialGroup()
                .addGap(232, 232, 232)
                .addComponent(pSubmitBtn)
                .addGap(51, 51, 51)
                .addComponent(backButton3)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        processLotsLayout.setVerticalGroup(
            processLotsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(processLotsLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addGroup(processLotsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(pBlockCbx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(processLotsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(pLotFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(processLotsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(pStatusCbx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(processLotsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clientFirstFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(processLotsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clientLastFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(34, 34, 34)
                .addGroup(processLotsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pSubmitBtn)
                    .addComponent(backButton3))
                .addGap(57, 57, 57))
        );

        parentPanel.add(processLots, "card5");

        jLabel5.setFont(new java.awt.Font("Sitka Heading", 1, 36)); // NOI18N
        jLabel5.setText("Generate Report");
        jLabel5.setToolTipText("");

        backButton4.setText("Back");
        backButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButton4ActionPerformed(evt);
            }
        });

        gTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Block No.", "Lot No.", "Size", "Price", "Status"
            }
        ));
        gTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(gTable);

        gBtn.setText("Generate");
        gBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout genRepLayout = new javax.swing.GroupLayout(genRep);
        genRep.setLayout(genRepLayout);
        genRepLayout.setHorizontalGroup(
            genRepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(genRepLayout.createSequentialGroup()
                .addGroup(genRepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(genRepLayout.createSequentialGroup()
                        .addGap(197, 197, 197)
                        .addComponent(jLabel5))
                    .addGroup(genRepLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 614, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(genRepLayout.createSequentialGroup()
                        .addGap(285, 285, 285)
                        .addGroup(genRepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(gBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(backButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        genRepLayout.setVerticalGroup(
            genRepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(genRepLayout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gBtn)
                .addGap(9, 9, 9)
                .addComponent(backButton4)
                .addGap(15, 15, 15))
        );

        parentPanel.add(genRep, "card6");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(parentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(parentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void modLotsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modLotsButtonActionPerformed
       
       parentPanel.removeAll();
       parentPanel.add(modifyLots);
       parentPanel.repaint();
       parentPanel.revalidate();
       
    }//GEN-LAST:event_modLotsButtonActionPerformed

    private void showLotButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showLotButtonActionPerformed
       
       parentPanel.removeAll();
       parentPanel.add(showLots);
       parentPanel.repaint();
       parentPanel.revalidate();
       
    }//GEN-LAST:event_showLotButtonActionPerformed

    private void procLotsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_procLotsButtonActionPerformed
       
       parentPanel.removeAll();
       parentPanel.add(processLots);
       parentPanel.repaint();
       parentPanel.revalidate();
       
    }//GEN-LAST:event_procLotsButtonActionPerformed

    private void genRepButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genRepButtonActionPerformed
       
       parentPanel.removeAll();
       parentPanel.add(genRep);
       parentPanel.repaint();
       parentPanel.revalidate();
       
    }//GEN-LAST:event_genRepButtonActionPerformed

    private void backButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButton1ActionPerformed
       parentPanel.removeAll();
       parentPanel.add(mainMenu);
       parentPanel.repaint();
       parentPanel.revalidate();
    }//GEN-LAST:event_backButton1ActionPerformed

    private void backButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButton3ActionPerformed
       parentPanel.removeAll();
       parentPanel.add(mainMenu);
       parentPanel.repaint();
       parentPanel.revalidate();
    }//GEN-LAST:event_backButton3ActionPerformed

    private void backButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButton4ActionPerformed
       parentPanel.removeAll();
       parentPanel.add(mainMenu);
       parentPanel.repaint();
       parentPanel.revalidate();
    }//GEN-LAST:event_backButton4ActionPerformed

    private void modifyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifyButtonActionPerformed
        // TODO add your handling code here:
        boolean hasError = false;
        try {
            if (Integer.parseInt(mBlockFld.getText())>blockLimit||Integer.parseInt(mLotFld.getText())>lotLimit) {
                throw new Exception("Block/Lot number is out of bounds");
            }
            else if (Integer.parseInt(mBlockFld.getText())<1||Integer.parseInt(mLotFld.getText())<1) {
                throw new Exception("Block/Lot number is zero or negative");
            }
            else if (Float.parseFloat(mPriceFld.getText())<minPrice||Float.parseFloat(mSizeFld.getText())<minSize) {
                throw new Exception("Input is lower than minimum values");
            }
            else if (Float.parseFloat(mPriceFld.getText())>maxPrice||Float.parseFloat(mSizeFld.getText())>maxSize) {
                throw new Exception("Input is higher than maximum values");
            }
            else
                manager.updateLot(Integer.parseInt(mBlockFld.getText()), Integer.parseInt(mLotFld.getText()), Float.parseFloat(mPriceFld.getText()) , Float.parseFloat(mSizeFld.getText()));
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(this,e.getMessage() ,"Error",JOptionPane.WARNING_MESSAGE);
            hasError = true;
        }
        if (!hasError) {
            mClearBtnActionPerformed(evt);
            JOptionPane.showMessageDialog(this, "Lot updated!");
        }
    }//GEN-LAST:event_modifyButtonActionPerformed

    private void backButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButton2ActionPerformed
        parentPanel.removeAll();
        parentPanel.add(mainMenu);
        parentPanel.repaint();
        parentPanel.revalidate();
    }//GEN-LAST:event_backButton2ActionPerformed

    private void mClearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mClearBtnActionPerformed
        // TODO add your handling code here:
        mSizeFld.setText("");
        mBlockFld.setText("");
        mLotFld.setText("");
        mPriceFld.setText("");
    }//GEN-LAST:event_mClearBtnActionPerformed

    private void sRefreshBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sRefreshBtnActionPerformed
        // TODO add your handling code here:
        DefaultTableModel mod = (DefaultTableModel) sTable.getModel();
        mod.setRowCount(0);
        for (int v = 0;v<blockLimit;v++) {
            for(int z = 0; z<lotLimit;z++) {
                mod.insertRow(mod.getRowCount(),new Object[] {
                manager.getArrayList().get(v).getBlockNum(), manager.getArrayList().get(v).getLots().get(z).getLotNum(), manager.getArrayList().get(v).getLots().get(z).getSize(), manager.getArrayList().get(v).getLots().get(z).getPrice()}
                );
            }
        }
        sTable.setAutoCreateRowSorter(true);
    }//GEN-LAST:event_sRefreshBtnActionPerformed

    private void pSubmitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pSubmitBtnActionPerformed
        // TODO add your handling code here:
        //need try block and JOptionPane response.
        boolean hasError = false;
        try {
            if (Integer.parseInt(pLotFld.getText())>lotLimit||Integer.parseInt(pLotFld.getText())<1) {
                throw new Exception("Lot number is out of bounds");
            }
            else if (clientFirstFld.getText().length()<1||clientLastFld.getText().length()<1) {
                throw new Exception("Empty field on client name");
            }
            else 
                manager.updateLotStatus(Integer.parseInt(pBlockCbx.getSelectedItem().toString()), Integer.parseInt(pLotFld.getText()), manager.generateClient(clientFirstFld.getText(), clientLastFld.getText(), clientFirstFld.getText().charAt(0)+clientLastFld.getText()), pStatusCbx.getSelectedItem().toString());
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(this,e.getMessage() ,"Error",JOptionPane.WARNING_MESSAGE);
            hasError = true;
        }
        if (!hasError) {
            //return back to default values
            pLotFld.setText("");
            clientFirstFld.setText("");
            clientLastFld.setText("");
            JOptionPane.showMessageDialog(this, "Status updated to: "+pStatusCbx.getSelectedItem().toString());
        }
    }//GEN-LAST:event_pSubmitBtnActionPerformed

    private void gBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gBtnActionPerformed
        // TODO add your handling code here:
        //outstream and show table
        DefaultTableModel mod = (DefaultTableModel) gTable.getModel();
        mod.setRowCount(0);
        for (int v = 0;v<blockLimit;v++) {
            for(int z = 0; z<lotLimit;z++) {
                mod.insertRow(mod.getRowCount(),new Object[] {
                manager.getArrayList().get(v).getBlockNum(), manager.getArrayList().get(v).getLots().get(z).getLotNum(), manager.getArrayList().get(v).getLots().get(z).getSize(), manager.getArrayList().get(v).getLots().get(z).getPrice(), manager.getArrayList().get(v).getLots().get(z).getStatus()}
                );
            }
        }
        gTable.setAutoCreateRowSorter(true);
    }//GEN-LAST:event_gBtnActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton1;
    private javax.swing.JButton backButton2;
    private javax.swing.JButton backButton3;
    private javax.swing.JButton backButton4;
    private javax.swing.JTextField clientFirstFld;
    private javax.swing.JTextField clientLastFld;
    private javax.swing.JButton gBtn;
    private javax.swing.JTable gTable;
    private javax.swing.JPanel genRep;
    private javax.swing.JButton genRepButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField mBlockFld;
    private javax.swing.JButton mClearBtn;
    private javax.swing.JTextField mLotFld;
    private javax.swing.JTextField mPriceFld;
    private javax.swing.JTextField mSizeFld;
    private javax.swing.JPanel mainMenu;
    private javax.swing.JButton modLotsButton;
    private javax.swing.JButton modifyButton;
    private javax.swing.JPanel modifyLots;
    private javax.swing.JComboBox<String> pBlockCbx;
    private javax.swing.JTextField pLotFld;
    private javax.swing.JComboBox<String> pStatusCbx;
    private javax.swing.JButton pSubmitBtn;
    private javax.swing.JPanel parentPanel;
    private javax.swing.JButton procLotsButton;
    private javax.swing.JPanel processLots;
    private javax.swing.JButton sRefreshBtn;
    private javax.swing.JTable sTable;
    private javax.swing.JButton showLotButton;
    private javax.swing.JPanel showLots;
    // End of variables declaration//GEN-END:variables
}
